services:
 nats-server:
  container_name: Nats_Server
  image: nats:latest

 client-gateway:
  container_name: Client_Gateway
  build:
   context: ./client-gateway
   dockerfile: dockerfile.prod
  image: client-gateway
  ports:
   - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
  environment:
   - PORT=${CLIENT_GATEWAY_PORT}
   - NATS_SERVERS=nats://nats-server:4222

 auth-ms:
  container_name: Authorization_Microservice
  build:
   context: ./auth-ms
   dockerfile: dockerfile.prod
  image: auth-ms
  environment:
   - PORT=3004
   - NATS_SERVERS=nats://nats-server:4222
   - DATABASE_URL=${AUTH_DATABASE_URL}
   - JWT_SECRET=${JWT_SECRET}

 products-ms:
  container_name: Product_Microservice
  build:
   context: ./product-ms
   dockerfile: dockerfile.prod
  image: product-ms
  environment:
   - PORT=3001
   - NATS_SERVERS=nats://nats-server:4222
   - DATABASE_URL=file:./dev.db

 orders-ms:
  container_name: Order_Microservice
  build:
   context: ./order-ms
   dockerfile: dockerfile.prod
   args:
    - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
  image: order-ms
  environment:
   - PORT=3002
   - DATABASE_URL=${ORDERS_DATABASE_URL}
   - NATS_SERVERS=nats://nats-server:4222

 payments-ms:
  container_name: Payment_Microservice
  build:
   context: ./payment-ms
   dockerfile: dockerfile.prod
  image: payment-ms
  ports:
   - ${PAYMENT_MICROSERVICE_PORT}:${PAYMENT_MICROSERVICE_PORT}
  environment:
   - PORT=${PAYMENT_MICROSERVICE_PORT}
   - NATS_SERVERS=nats://nats-server:4222
   - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
   - ENDPOINTSECRET=${ENDPOINTSECRET}
   - SUCCESS_URL=${SUCCESS_URL}
   - CANCEL_URL=${CANCEL_URL}
